### ISSUE TITLE
docs: tracking issue for adding various guides under /guides

### ISSUE THREAD

**Issue by profnandaa** [kubernetes-sigs/sig-windows-tools#255]
This is a tracking issue to add various useful guides related to Windows on Kubernetes. Can really be anything. Please feel free to suggest here guides that need to be added.

**TODO:**

- [ ] Monitoring with LogMonitor, assign: @profnandaa
- [ ] Setting up ELK stack for Windows pods; assign: @profnandaa
- [ ] TBD

**Comment by jsturtevant** [comment]
xref: https://github.com/kubernetes-sigs/sig-windows-tools/issues/217

These are great ideas! If possible, would like to see docs go into the upstream repositories to lower the maintenance on sig-windows.

**Comment by profnandaa** [comment]
@jsturtevant -- possible to have them here as an incubator/WIP and then move them over to upstream once "matured"? Or do we run a risk of more management overhead? :thinking:

**Comment by jsturtevant** [comment]
once they get merged here, they get used and then we get lots of folks trying them out (this has happened with all the CNI work). Since we aren't always the experts on the surrounding technology it becomes difficult to help and folks get frustrated.  

Don't get me wrong I think these are fantastic things for us to help contribute back to projects to make it easier for Windows users.  Using this repo as a way to track and plan works for me.  Also having a list where we can point them out to all the new docs would be good too.

**Comment by profnandaa** [comment]
@jsturtevant -- got it, makes sense.

**Comment by profnandaa** [comment]
So, the guides section could just be hyper-links with brief commentaries, right?
