### ISSUE TITLE
document what versions of Windows are supported

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/sig-windows-tools#90]
the users are confused...:
https://github.com/kubernetes-sigs/sig-windows-tools/issues/61
we have other similar tickets here.

AFAIK, this project (kubeadm + sig-windwos_tools) supports 1903 only.

the k8s.io website documentation needs to be _clear_ what versions of Windows we are supporting:
- (ideally a matrix) what versions of Windows our custom flannel / kube-proxy images in this repo support?
- (ideally a matrix) what the official pause image supports?

/priority important-soon
/sig windows
/kind documentation
/assign @benmoss @marosset

**Comment by neolit123** [comment]
/help

documentation changes can be sent to this page:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

**Comment by gimlichael** [comment]
**UPDATE FOR 1909 SERVERS**

Just my small contribution to the project; I looked into both having a nanoserver and a servercore version of the two deamon-sets (kube-proxy and flannel). 

However, I was only able to get the servercore version to work .. but it is gigantic 5 GB vs. 500 MB in nano-edition .. when I have rested, i think i will look more into it, as it takes forever in overhead to retrieve the servercore version.

For now, for those who are interested, you can test it here:

Instead of `sigwindowstools/flannel:0.12.0` use `gimlichael/k8s-sigwindowstools-flannel:k8s-1.18.3-windows-1909-servercore`

Instead of `sigwindowstools/kube-proxy:1.18.3` use `gimlichael/k8s-sigwindowstools-kube-proxy:k8s-1.18.3-windows-1909-servercore`

Happy K8S on Win 1909 to you all :-)

**Comment by Tehacz** [comment]
Does it mean flannel will not work properly on 1809 build?

**Comment by AMoghrabi** [comment]
Hello. I'm currently running 1809. Looks like my flannel pod is running fine but kube-proxy is failing (I'm running K8s 1.16.11).

Will 1809 not work with this setup? Thanks!

**Comment by marosset** [comment]
/remove-lifecycle stale

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support has a support table for components built in kubernetes/kubernetes (kubelet, kubeproxy, kubectl, etc)

I can create a table for supported pause images.
Should that get added on k8s.io docs or here?

**Comment by neolit123** [comment]
users seem to flow from the k8s.io documentation to here, so it seems better to have it at k8s.io.

**Comment by jsturtevant** [comment]
#111 added images for the Windows OS (1809, 1903, 1909, 2004) for kube-proxy and flannel images that are built from this repository.
