### ISSUE TITLE
1903 Not working

### ISSUE THREAD

**Issue by Tehacz** [kubernetes-sigs/sig-windows-tools#93]
Hi i am trying to setup kubernetes cluster on 1903 like in documentation:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

But i get the following error instead,

I use image: sigwindowstools/flannel:0.12.0

Please help, starting windows cluster is crucial for my company

 Warning  FailedCreatePodSandBox  4s (x4 over 7s)    kubelet, winkube-w2  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-windows-amd64-fsnkw": Error response from daemon: hcsshim::CreateComputeSystem 0910a72ab593c5658d88b4f268fede8d4858c309ec790f7fe23a8805bafe01f9: The container operating system does not match the host operating system.

**Comment by jsturtevant** [comment]
The flannel containers are only currently only built for WS 2019. You can build the image yourself as a temporary work around.

**Comment by fourpastmidnight** [comment]
I got this working on Windows Server 2019 2004 (10.0.19041.508). I did as @jsturtevant said. I built my own images. 3, to be exact. I needed to build my own GoLang image, kube-flannel image, and kube-proxy image. You can find my script module at https://github.com/fourpastmidnight/kubewin.

The script module orchestrates all of this&mdash;pulling and building the images, allowing the user to setup an SSH key and authorize it on the master control plane, installing all the bits and services and finally joining the cluster. It needs a bit of polish, but it does work. One thing, though, when joining the cluster the script appears to error out because of exceeding the timeout. But within a few more seconds, the kube-proxy-windows pod started running and the node shows up as ready:

```
my-user@k8s-master:~$ kubectl get nodes
NAME              STATUS   ROLES    AGE    VERSION
k8s-master        Ready    master   9d     v1.19.3
k8s-worker-w001   Ready    <none>   113s   v1.19.3
```

To use the script module, after importing it:

1. Run `New-KubernetesWindowsNodeConfiguration` to create a configuration object (which was "inspired" by `KubeClusterVxlan.json`, which can be found in this repo).
2. Run `New-WindowsKubernetesClusterNode`
3. If you selected `N` to join the cluster at the end of step 2, you can simply run `Join-KubernetesCluster` to join the node to the cluster.

That's it.

Like I said, it still needs some polish&mdash;particularly `Join-KubernetesCluster`&mdash;but it _does_ work.

**Comment by fourpastmidnight** [comment]
I should add to the above, with respect to my script module, that if you are NOT using Windows Server 2019 1809, that you should then **only follow steps 1 &ndash; 3** at [Adding Windows nodes | Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/). Step 4 will be handled by my `New-WindowsKubernetesClusterNode` cmdlet, and obviously, `PrepareNode.ps1` is replaced in entirety by my script module.

**Comment by jsturtevant** [comment]
@fourpastmidnight Thanks for following up! Working on adding other image versions in #111.  Are there any improvements in your scripts that could be folded back into the scripts in this repository?

**Comment by fourpastmidnight** [comment]
I think the biggest thing is that if you're using a version of Windows Server 2019 >1809, you need to build custom docker images based on the version of Windows Server 2019 being used, as many have noted in various GH issues.

So the most important change, here, was modifying `flannel-[overlay|gw-host].yml` (depending on which network type you're using) and `kube-proxy.yml` with the correct image since currently, these files pull publicly available images which _only_ support Windows Server 2019 LTSC2019/1809.

For my particular script module, I did not go through the effort to host a docker repository to which I could push the custom images I created. So I also needed to add `imagePullPolicy: never` to both of those YAML DaemonSet files. Perhaps this should be an option that can be set (with the default being to not override the `imagePullPolicy` at all)?
