### ISSUE TITLE
Support for kube-proxy:v1.16.11

### ISSUE THREAD

**Issue by AMoghrabi** [kubernetes-sigs/sig-windows-tools#95]
Hello,

Do you provide support for `sigwindowstools/kube-proxy:v1.16.11`? I'm running Windows 1809 and K8s version `1.16.11`. The flannel pods are running fine and my Windows node is in a `Ready` state. However, the pod responsible for the above image is stuck in an `ErrImagePull` state.

Attempting to pull the image on the host leads to this error: 

```
Error response from daemon: manifest for sigwindowstools/kube-proxy:v1.16.11 not found: manifest unknown: manifest unknown
```

I've looked at Docker Hub and unfortunately I don't see a version for 1.16.11. Is that something easy to get going or are there some technical limitations? If it is possible, I may be able to contribute. 

Thanks!

**Comment by AMoghrabi** [comment]
I've reviewed our environment and I think upgrading to 1.17.7 is fine for us, so this isn't urgent by any means. Though if you'd still would like me to contribute & this is possible to do, let me know and I can get started. Thanks!

**Comment by benmoss** [comment]
I think we chose this because 1.17.0 was the first release of kubelet that supported starting `hostNetwork: true` pods that let us bootstrap CNI as pods. https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/hack/publish-kubeproxy.go#L15 is all that would need to change to get the bot to produce the images, but I don't think 1.16.11 kubelet would work.

**Comment by AMoghrabi** [comment]
Makes sense, thank you!
